### ISSUE TITLE
On init is always 'sm' breakpoint set

### ISSUE THREAD

**Issue by devzom** [vanhoofmaarten/nuxt-mq#124]
* **I'm submitting a ...**
[x] bug report

* **Summary**

The problem is whenever I refresh page the starting breakpoint is 'sm' instead of 'lg' which I've set in nuxt.config.
So if I am using v-show/v-if for not showing exact element it's showing it for a second or two. ;]

What's the workaround for it?

the same happened on codesandbox -> [https://codesandbox.io/s/nuxt-mq-issue-92-forked-eiqzk?file=/nuxt.config.js](url)

looks like it doesn't read the defaultBreakpoint from nuxt.config

**Comment by vanhoofmaarten** [comment]
Hi @devzom. Interesting use case you have here. `nuxt-mq` currently doesn't support default values for the `mq` method inside a `<client-only>` tag. I'll have to dig a little deeper to find out if this is possible or if you're up for it, you're always welcome to share a PR 😃.

There are several workarounds depending on your use case.
- Show a loader or placeholder, like nuxt suggest: https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component
- Move the `v-if` outside of the `client-only` so that you have access to the `defaultBreakpoint`

Does this answer help you along?

**Comment by devzom** [comment]
Hey @vanhoofmaarten, thank You for Your time ⌚ and the answer! I've found out similar solutions to use in the project, but I'll the one You've suggest. Thanks :) If I'm able to hack nuxt SSR then I'll made a PR :P
