### ISSUE TITLE
[Vue warn]: Property or method "$mq" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

### ISSUE THREAD

**Issue by heshamelmasry77** [vanhoofmaarten/nuxt-mq#4]
i get this warning when i use $mq i dunno why but i really wanna use the $mq. please advice

**Comment by laportem** [comment]
got the same warning but only in Nuxt 2.0+

**Comment by heshamelmasry77** [comment]
The solution is to put anything outside the  ``` <nuxt/> ``` 
tag in a ```<no-ssr>``` tag
example :
```
	<no-ssr>
			<app-main-header />
		</no-ssr>
		<nuxt />
    <no-ssr>
			<app-email-sms-alerts />
		</no-ssr>
```

**Comment by laportem** [comment]
Won't help me. I ended up doing this:

Instead of this
<v-flex v-bind:class="[{'text-xs-center': this.$mq === 'mobile' }, {'text-xs-right': this.$mq !== 'mobile' }]">

I used computed
<v-flex v-bind:class="[{'text-xs-center': isMobile }, {'text-xs-right': !isMobile }]">
computed: {
    isMobile() {
      if (this.$mq === 'mobile') {
        return true;
      } else {
        return false;
      }
    },
}

Seems to get rid go the warning

**Comment by vanhoofmaarten** [comment]
This module now supports SSR, which in turn also solves this issue.
