### ISSUE TITLE
DOM mismatch when using mq-layout

### ISSUE THREAD

**Issue by webcoderkz** [vanhoofmaarten/nuxt-mq#60]
nuxt.config.js:

```
mq: {
  defaultBreakpoint: 'md',
  breakpoints: {
    sm: 640,
    md: 1250,
    lg: Infinity
  }
},
```

using in a component.vue:

```
<mq-layout mq="sm">content for sm breakpoint</mq-layout>
```

Then i get an error:

![image](https://user-images.githubusercontent.com/5739191/84738093-14c68d80-afcb-11ea-80be-500950e828c5.png)

If i change `defaultBreakpoint` to `sm` then it works, but if i use `<mq-layout mq="md">content for md breakpoint</mq-layout>` then i get DOM mismatch error again.

**Comment by vanhoofmaarten** [comment]
Hi @webcoderkz,

I can only seem to reproduce this error on the occasion that another component is not registered correctly.

Going on further on (apologies for the delay, had troubles dedicating time to this issue), I've created a sandbox, in which I believe I recreated an environment closely to that of your project.

* Editor: https://codesandbox.io/s/github/vanhoofmaarten/nuxt-mq-issue-60
* Full preview: https://3x44q.sse.codesandbox.io/

Notice that:
* On the homepage (/) there is a warning that is only shown on the `sm`breakpoint. No issues
* On the about page, the same warning and `mq-layout` code reused. But the `Vue warn ...` is raised here because I used a non-registered Vue Component `v-main` instead of `v-content`

Does this help or solve your issue? If not, could you provide me with a codesandbox where the issue is reproduced? Thanks!

**Comment by webcoderkz** [comment]
Just had a look at your condesandbox, you have an alert:

```
    <mq-layout mq="sm">
      <v-alert type="warning">
        Warning only shown on 'sm' devices.
      </v-alert>
    </mq-layout>
```

But it doesn't show up in a page source, hence your DOM is consistent. Why?

**Comment by vanhoofmaarten** [comment]
In our example, the alert won't be Server Side Rendered, because `nuxt-mq` only takes the `defaultBreakpoint` in to account during SSR. Therefore, it is also not in the page source. As soon as the component is mounted, `nuxt-mq` kicks in and adds the element to the VDOM on `sm` devices.

It is one of the limitations of conditionally rendering (V)DOM-elements using a browser-exclusive feature, like media-queries in this case.

I've updated the example with an info alert on the homepage. This alert **is** rendered on the server and visible in the page source, because its visible on the same value as our `defaultBreakpoint`: `md`

Does this answer your question?

**Comment by webcoderkz** [comment]
But when you resize the window, it adds `sm` alert to VDOM and it's inconsistent, but your example is not showing the errors in a console. Let me try to sandbox my project.

**Comment by webcoderkz** [comment]
Guess, it was my own issues, i restarted IDE and errors are gone, thanks for your time.

**Comment by vanhoofmaarten** [comment]
With pleasure. 

Is this issue related to #56? If so, I can close that one off too.

Good luck with your project!
